#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config border_width         0
bspc config window_gap           5
bspc config top_padding          25
bspc config bottom_padding       10
bspc config left_padding         10
bspc config right_padding        10

bspc config split_ratio          0.50
bspc config single_monocle       false
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config pointer_modifier mod4
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Emacs state=tiled follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

./.config/bspwm/scripts/autostart.sh
