require("chain.plugins-setup")
require("chain.plugins.comment")
require("chain.plugins.telescope")
require("chain.plugins.lualine")
require("chain.plugins.nvim-tree")
require("chain.core.color")
require("chain.core.option")
require("chain.core.keymap")
